# MySQL. Versions 5.5.8 and up are supported.

default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default